server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.financial.control: DEBUG

services:
  user-service:
    url: ${USER_SERVICE_URL:http://user-service:8081}
  transaction-service:
    url: ${TRANSACTION_SERVICE_URL:http://transaction-service:8082}
  investment-service:
    url: ${INVESTMENT_SERVICE_URL:http://investment-service:8083}

---
spring:
  config:
    activate:
      on-profile: docker
