global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'transaction-service'
    static_configs:
      - targets: ['transaction-service:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'investment-service'
    static_configs:
      - targets: ['investment-service:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
